preset: psr2

linting: true

risky: true

enabled:
  - no_unused_imports
  - no_useless_else
  - phpdoc_add_missing_param_annotation
  - phpdoc_no_package
  - phpdoc_scalar
  - phpdoc_types

finder:
  name:
    - "*.php"
  path:
    - "src"
    - "tests"

